[project]
name = "edital_summarizer"
version = "0.1.0"
description = "edital-summarizer using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = ["crewai[tools]>=0.118.0,<1.0.0"]

[project.scripts]
edital_summarizer = "edital_summarizer.main:run"
run_crew = "edital_summarizer.main:run"
train = "edital_summarizer.main:train"
replay = "edital_summarizer.main:replay"
test = "edital_summarizer.main:test"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.crewai]
type = "crew"

[tool.poetry]
name = "edital-summarizer"
version = "0.1.0"
description = "A CrewAI-based tool for summarizing bidding documents"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
crewai = "*"
PyPDF2 = "*"
pandas = "*"
openpyxl = "*"
python-dotenv = "*"
typer = { extras = ["all"], version = "*" }
pyyaml = "*"
