target_analysis_task:
  description: |
    Analise o documento para determinar se é relevante para o alvo '{target}' e se atende ao volume mínimo de {threshold} unidades.
    
    IMPORTANTE: Você DEVE retornar APENAS um JSON válido com os seguintes campos:
    - target_match: boolean indicando se o documento é relevante para o alvo
    - volume: número inteiro indicando o volume total de operações (0 se não for relacionado a dispositivos)
    
    Exemplo de resposta válida:
    {
        "target_match": true,
        "volume": 1000
    }
    
    NÃO inclua nenhum texto adicional ou explicações. Apenas o JSON.
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "JSON com target_match e volume"
  agent: target_analyst_agent

summary_task:
  description: |
    Gere um resumo conciso e estruturado do edital, seguindo exatamente este formato:

    **Cidade/UF**
    - Identifique a cidade e UF do edital
    - Retorne no formato "Cidade/UF" ou "N/A" se não conseguir identificar

    **Objeto da Licitação**
    - Objetivo principal em uma linha
    - Modalidade e tipo de licitação

    **Lotes e Quantidades**
    - Lista direta dos lotes com quantidades e especificações principais
    - Use tópicos curtos e diretos
    - Exemplo:
      * Lote 1: 3 Frigobares (116L, classe A)
      * Lote 2: 1 Ar-condicionado (24.000 BTUs, Split)

    **Prazos Importantes**
    - Data de abertura
    - Prazo de entrega
    - Validade da proposta

    **Condições Principais**
    - Requisitos essenciais para participação
    - Documentação necessária
    - Restrições relevantes

    O resumo deve ser:
    1. Direto e objetivo
    2. Estruturado em tópicos curtos
    3. Focado nas informações mais relevantes
    4. Sem introduções ou conclusões desnecessárias
    5. Em português claro
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "Resumo conciso e estruturado do edital incluindo cidade/UF"
  agent: summary_agent

justification_task:
  description: |
    Gere uma justificativa clara, direta e objetiva para a decisão de relevância.
    
    Target: {target}
    Threshold: {threshold}
    Target Match: {target_match}
    Threshold Match: {threshold_match}
    Is Relevant: {is_relevant}
    
    A justificativa deve ser:
    1. Direta e objetiva - explique em poucas frases
    2. Focada nos pontos principais que determinam a relevância
    3. Sem repetições ou explicações desnecessárias
    4. Em português claro e acessível
    
    Estrutura sugerida:
    1. Primeira frase: conclusão direta (relevante ou não)
    2. Segunda frase: motivo principal
    3. Terceira frase (se necessário): detalhe específico do documento
    
    Exemplo de justificativa concisa:
    "O edital não é relevante para o target 'Fornecimento de Tablets para Educação'. O objeto da licitação é a aquisição de equipamentos eletroeletrônicos e eletrodomésticos para a Defesa Civil, sem menção a tablets ou dispositivos educacionais. Os lotes especificam apenas frigobares, ar-condicionados e outros equipamentos não relacionados à educação."
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "Justificativa clara, direta e objetiva"
  agent: justification_agent

city_inference_task:
  description: |
    Analise o documento para identificar a cidade e UF correta do edital.
    
    Você deve:
    1. Procurar por menções a órgãos públicos (Prefeitura, Secretaria, etc.)
    2. Identificar endereços e localizações mencionadas
    3. Extrair a cidade e UF relacionada
    4. Validar se a informação faz sentido no contexto
    
    IMPORTANTE: Retorne APENAS a cidade e UF no formato "Cidade/UF".
    Se não conseguir identificar com certeza, retorne "N/A".
    
    Exemplos de respostas válidas:
    - "Manaus/AM"
    - "São Paulo/SP"
    - "Brasília/DF"
    - "N/A"
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "Cidade/UF ou N/A"
  agent: city_inference_agent
