target_analysis_task:
  description: |
    Analise o documento para determinar se é relevante para o alvo '{target}' e se atende ao volume mínimo de {threshold} unidades.
    
    IMPORTANTE: Você DEVE retornar APENAS um JSON válido com os seguintes campos:
    - target_match: boolean indicando se o documento é relevante para o alvo
    - volume: número inteiro indicando o volume total de operações (0 se não for relacionado a dispositivos)
    
    Exemplo de resposta válida:
    {
        "target_match": true,
        "volume": 1000
    }
    
    NÃO inclua nenhum texto adicional ou explicações. Apenas o JSON.
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "JSON com target_match e volume"
  agent: target_analyst_agent

summary_task:
  description: |
    Gere um resumo detalhado do edital, incluindo:
    - Objeto da licitação
    - Quantidades mencionadas
    - Especificações técnicas relevantes
    - Prazos e valores
    - Outras informações importantes
    
    O resumo deve ser:
    1. Claro e conciso
    2. Estruturado em tópicos
    3. Focado em informações relevantes
    4. Baseado apenas no conteúdo do documento
    5. Em português
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "Resumo detalhado do edital"
  agent: summary_agent

justification_task:
  description: |
    Gere uma justificativa clara, direta e objetiva para a decisão de relevância.
    
    Target: {target}
    Threshold: {threshold}
    Target Match: {target_match}
    Threshold Match: {threshold_match}
    Is Relevant: {is_relevant}
    
    A justificativa deve ser:
    1. Direta e objetiva - explique em poucas frases
    2. Focada nos pontos principais que determinam a relevância
    3. Sem repetições ou explicações desnecessárias
    4. Em português claro e acessível
    
    Estrutura sugerida:
    1. Primeira frase: conclusão direta (relevante ou não)
    2. Segunda frase: motivo principal
    3. Terceira frase (se necessário): detalhe específico do documento
    
    Exemplo de justificativa concisa:
    "O edital não é relevante para o target 'Fornecimento de Tablets para Educação'. O objeto da licitação é a aquisição de equipamentos eletroeletrônicos e eletrodomésticos para a Defesa Civil, sem menção a tablets ou dispositivos educacionais. Os lotes especificam apenas frigobares, ar-condicionados e outros equipamentos não relacionados à educação."
    
    CONTEÚDO DO DOCUMENTO:
    {document_content}
  expected_output: "Justificativa clara, direta e objetiva"
  agent: justification_agent
