target_analysis_task:
  description: |
    Analise o documento fornecido para determinar se ele é relevante para o target '{target}' e se atende ao threshold mínimo de {threshold} unidades.

    IMPORTANTE:
    1. O documento DEVE ser analisado em português
    2. O documento DEVE ser analisado em relação ao target '{target}'
    3. Se o target for relacionado a dispositivos (notebook, tablet, celular, etc.), verifique se a quantidade mencionada atende ao threshold mínimo de {threshold} unidades
    4. Se a quantidade não puder ser determinada com certeza, retorne 'inconclusive'
    5. Se a quantidade for menor que o threshold, retorne 'false'
    6. Se a quantidade for maior ou igual ao threshold, retorne 'true'
    7. Se o target não for relacionado a dispositivos, ignore o threshold e retorne 'true' se o documento for relevante
    8. NÃO inclua nenhum texto explicativo antes ou depois da resposta
    9. NÃO retorne um JSON ou qualquer outro formato
    10. A resposta DEVE ser APENAS uma das seguintes opções: 'true', 'false' ou 'inconclusive'
    11. Se o documento estiver vazio ou contiver muito pouco conteúdo, retorne 'false'
    12. Considere variações de termos (ex: "equipamentos eletrônicos" pode incluir tablets)
    13. Analise o objeto da licitação em detalhes
    14. Seja assertivo na resposta, evitando "inconclusive" quando possível

    DOCUMENTO:
    {document_content}
  expected_output: "true, false ou inconclusive"
  agent: target_analyst_agent

summary_task:
  description: |
    Gere um resumo executivo do documento fornecido, focando no target '{target}'.

    IMPORTANTE:
    1. O resumo DEVE ser baseado APENAS no conteúdo do documento fornecido
    2. O resumo DEVE ser em português
    3. O resumo DEVE ser informativo e útil
    4. NÃO inclua nenhum texto em inglês
    5. NÃO inclua nenhum texto explicativo antes ou depois do resumo
    6. NÃO retorne "I now can give a great answer" ou qualquer outro texto em inglês
    7. O resumo DEVE ser um texto completo e coerente em português
    8. NÃO gere um resumo genérico sobre o target
    9. NÃO retorne um JSON ou qualquer outro formato
    10. Se o documento não contiver informações suficientes, retorne uma justificativa clara
    11. A resposta DEVE ser APENAS o resumo em português, sem nenhum texto adicional
    12. NÃO inclua palavras como "Thought:", "Final Answer:" ou qualquer outro prefixo
    13. O resumo DEVE conter:
        - Objeto da licitação
        - Quantidade de itens (se mencionada)
        - Principais especificações técnicas
        - Prazo de entrega (se mencionado)
        - Valor estimado (se mencionado)
    14. Se não encontrar informações suficientes, retorne: "Edital de licitação para {target}. Conteúdo disponível para análise, mas não foi possível gerar um resumo detalhado."
    15. Organize as informações em tópicos claros
    16. Destaque informações relevantes para o target
    17. Seja específico e evite generalizações

    DOCUMENTO:
    {document_content}
  expected_output: "Resumo do documento em português"
  agent: summary_agent

justification_task:
  description: |
    Gere uma justificativa clara e objetiva para a não geração do resumo.

    Considere os seguintes cenários:
    1. Se o documento não for relevante para o target '{target}'
    2. Se o número de referências ao target for menor que o threshold mínimo de {threshold} unidades
    3. Se a quantidade não puder ser determinada com certeza (status: {threshold_status})
    4. Se houver problemas na leitura do documento
    5. Se o documento estiver vazio ou não contiver informações suficientes

    DOCUMENTO:
    {document_content}

    A justificativa deve ser profissional e técnica, explicando o motivo da não geração do resumo.

    IMPORTANTE:
    1. A justificativa DEVE ser em português
    2. A justificativa DEVE ser clara e objetiva
    3. NÃO inclua nenhum texto em inglês
    4. NÃO inclua nenhum texto explicativo antes ou depois da justificativa
    5. NÃO retorne o mesmo texto do resumo
    6. A justificativa DEVE explicar POR QUE o documento não é relevante ou não atende ao threshold
    7. A justificativa DEVE ser baseada APENAS no conteúdo do documento fornecido
    8. NÃO gere uma justificativa genérica, mas sim baseada no conteúdo específico do documento
    9. NÃO retorne um JSON ou qualquer outro formato
    10. NÃO retorne "I now can give a great answer" ou qualquer outro texto em inglês
    11. Se o documento estiver vazio ou contiver muito pouco conteúdo, retorne: "O documento está vazio ou contém muito pouco conteúdo para análise."
    12. Se o documento contiver conteúdo mas não for possível determinar a relevância, retorne: "O documento contém conteúdo, mas não foi possível determinar com certeza sua relevância para o target '{target}'."
    13. Mencione aspectos específicos do documento que justificam a decisão
    14. Seja técnico e objetivo na justificativa
    15. Evite justificativas genéricas

  expected_output: "Justificativa em português"
  agent: justification_agent
