research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

metadata_extraction:
  description:
    en: |
      Extract the following metadata from the document text:
      - Title
      - Organization/Entity
      - Publication Date
      - Deadline Date
      - Object/Subject
      - Reference Number
      - Estimated Value
      - Contact Information

      Return the data in JSON format.
    pt-br: |
      Extraia os seguintes metadados do texto do documento:
      - Título
      - Organização/Entidade
      - Data de Publicação
      - Data Limite
      - Objeto
      - Número de Referência
      - Valor Estimado
      - Informações de Contato

      Retorne os dados em formato JSON.

executive_summary:
  description:
    en: "Generate a concise executive summary focusing on key points and decisions needed."
    pt-br: "Gere um resumo executivo conciso focando nos pontos-chave e decisões necessárias."

technical_summary:
  description:
    en: "Generate a detailed technical summary focusing on specifications and requirements."
    pt-br: "Gere um resumo técnico detalhado focando em especificações e requisitos."
