identifier_task:
  description: >
    Examine o documento e extraia APENAS os seguintes campos em formato JSON:
    - public_notice: número do edital
    - bid_number: número da licitação
    - process_id: número do processo
  expected_output: >
    Um JSON com os identificadores extraídos do documento
  agent: identifier_agent

organization_task:
  description: >
    Analise o documento e extraia APENAS os seguintes campos em formato JSON:
    - agency: nome do órgão responsável
    - city: cidade onde o evento ocorre
    - phone: telefone para contato
    - website: site mencionado no documento
  expected_output: >
    Um JSON com informações sobre as organizações e contatos
  agent: organization_agent

dates_task:
  description: >
    Extraia do documento APENAS as datas importantes em formato JSON com a chave 'dates'.
    Inclua datas de publicação, abertura, encerramento e outras datas relevantes.
  expected_output: >
    Um JSON com as datas importantes do edital
  agent: dates_agent

subject_task:
  description: >
    Extraia o objeto principal do edital em formato JSON com a chave 'object'.
    O objeto deve descrever do que se trata o edital em uma frase objetiva.
  expected_output: >
    Um JSON com o objeto principal do edital
  agent: metadata_agent

executive_summary:
  description: >
    Crie um resumo executivo conciso e claro do documento que destaque
    os pontos mais importantes para tomadores de decisão. O resumo deve
    ter no máximo 300 palavras e focar nos aspectos de negócio e financeiros.
  expected_output: >
    Um resumo executivo conciso com os pontos-chave do edital
  agent: executive_summary_agent

technical_summary:
  description: >
    Gere um resumo técnico detalhado do documento com foco nas especificações
    técnicas, requisitos e obrigações da licitação. Estruture o resumo em tópicos
    e inclua valores, prazos e critérios técnicos relevantes.
  expected_output: >
    Um resumo técnico detalhado das especificações e requisitos do edital
  agent: technical_summary_agent
