target_analysis_task:
  description: |
    Analise o documento e determine se ele é relevante para o target: {target}
    O target pode incluir uma descrição entre parênteses. Por exemplo:
    - Se o target for "RPA (Automação de Processos Robotizados)", você deve verificar se o documento
      menciona RPA, automação de processos, processos robotizados ou termos relacionados.
    - Se o target for "Tablet (Dispositivo móvel)", você deve verificar se o documento
      menciona tablets, dispositivos móveis ou termos relacionados.

    Considere tanto o termo principal quanto a descrição entre parênteses ao fazer a análise.
    
    CRITÉRIOS DE RELEVÂNCIA:
    1. O documento DEVE conter referências diretas ao target ou termos relacionados
    2. O documento DEVE ter conteúdo relevante para o contexto do target
    3. Documentos que não mencionam o target ou termos relacionados NÃO são relevantes
    4. Documentos que mencionam o target mas não têm conteúdo relevante NÃO são relevantes
    5. Documentos que são apenas formulários, cotações ou documentos administrativos NÃO são relevantes
    6. Documentos que não têm relação com o contexto do target NÃO são relevantes

    IMPORTANTE: 
    1. Retorne APENAS 'true' se o documento for relevante para o target
    2. Retorne APENAS 'false' se o documento NÃO for relevante para o target
    3. NÃO inclua nenhum outro texto na resposta
    4. NÃO explique sua decisão
    5. NÃO adicione pontuação ou espaços extras
    6. Use APENAS letras minúsculas

    DOCUMENTO:
    {document_content}
  expected_output: "true ou false"
  agent: target_analyst_agent

summary_task:
  description: |
    Gere um resumo executivo do documento, focando em aspectos relevantes para o target: {target}
    O resumo deve ser conciso e informativo, destacando os pontos mais importantes relacionados ao target.
    IMPORTANTE: 
    1. O resumo DEVE ser em português
    2. O resumo DEVE ser relevante para o target '{target}'
    3. O resumo DEVE ser informativo e útil
    4. NÃO inclua nenhum texto em inglês
    5. NÃO inclua nenhum texto explicativo antes ou depois do resumo
    6. NÃO retorne "I now can give a great answer" ou qualquer outro texto em inglês
    7. O resumo DEVE ser um texto completo e coerente em português

    DOCUMENTO:
    {document_content}
  expected_output: "Resumo executivo em português"
  agent: summary_agent

justification_task:
  description: |
    Gere uma justificativa clara e objetiva para a não geração do resumo.
    Considere os seguintes cenários:
    1. Se o documento não for relevante para o target '{target}'
    2. Se o número de referências ao target for menor que o threshold

    A justificativa deve ser profissional e técnica, explicando o motivo da não geração do resumo.
    IMPORTANTE: 
    1. A justificativa DEVE ser em português
    2. A justificativa DEVE ser clara, objetiva e ter no máximo 3 frases.
    3. Seja direto, não repita o contexto do edital.
    4. NÃO inclua nenhum texto em inglês
    5. NÃO inclua nenhum texto explicativo antes ou depois da justificativa
    6. A justificativa DEVE explicar POR QUE o documento não é relevante para o target
    7. NÃO mencione problemas de leitura ou processamento do documento
    8. Foque em explicar a falta de relevância do conteúdo do documento para o target

    DOCUMENTO:
    {document_content}
  expected_output: "Justificativa técnica em português explicando por que o documento não é relevante para o target"
  agent: justification_agent
